services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bumperplus_dev_server
    ports:
      - "8000:80"
    volumes:
      # Map the whole public folder
      - ./src/public:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    stdin_open: true
    tty: true
    restart: always

networks:
  default:
    name: bumperplus_network