# <VirtualHost *:80>
#     DocumentRoot /Users/johnmilner/Sites/CREATIVE-DEV-MISC/penryn-starter/src
# </VirtualHost>

<VirtualHost *:80>
    ServerName my-mvc-app.localhost
    ProxyPreserveHost On
    ProxyRequests Off
    ProxyPass / http://localhost:8081/
    ProxyPassReverse / http://localhost:8081/
</VirtualHost>

